### ISSUE TITLE
please remove 4.0 from PAUSE immediately

### ISSUE THREAD

**Issue by karenetheridge** [makamaka/JSON-PP#40]
As expressed on IRC, propagating JSON::XS's bad decisions to the pure-perl version is wrong and will break applications. This is especially serious as JSON::PP is dual-life in core and perl itself will be affected.

JSON::PP's behaviour should not change just because one of the XS backends changed its defaults. The PP version must remain consistent.

If you delete this distribution from PAUSE and then force-reindex the last 3.x release, no one will install 4.0 even though it takes 3 days for the deletion to propagate.  Then, a new 4.0 release can be made later (if desired) as long as the tarball filename is different.

**Comment by karenetheridge** [comment]
cc @charsbar

**Comment by charsbar** [comment]
Please do not spam the same issue, not to scatter discussion.

**Comment by karenetheridge** [comment]
It's not spam. What JSON::PP does is not the same issue as what JSON.pm does.

I really wish this had been brought up (e.g. on the cpan-workers mailing list) before being released as stable, as there are lots of downstream ramifications to perl core and the toolchain.

**Comment by charsbar** [comment]
It is, because the change has nothing to do with JSON::PP as a core module to encode/decode META.json, because CPAN::Meta::Spec is well defined and there's no room where a nonref top value pops in. The issues of JSON::PP out of that context reduce to the same as JSON, and I don't think they are for cpan-workers in particular.

It seems to me that you are just overreacting against the phrase "backward incompatibility" without understanding what it really is or without knowing other backward incompatible problems around JSON modules in general. haarg's changing number detection patch for JSON::PP, Cpanel::JSON::XS's change of encode_json prototype, and its boolean tweak that led to a warning from JSON::PP all have broken something, but have you asked them to pull those incompatible changes away from CPAN?
