### ISSUE TITLE
Add option to give more lines of context upon errors

### ISSUE THREAD

**Issue by jidanni** [makamaka/JSON-PP#42]
```
$ json_pp < $@
invalid character encountered while parsing JSON string, at character offset 32985 (before "\n          },\n    ...") at /usr/bin/json_pp line 40.

```

1. We can never find what you are talking about with just that smidgen of context. So please add an option to give as many lines as we need.
2. Say "character (not byte) offset", or "byte (not character) offset" so we can be sure what you are talking about. Thank you. 

No at those places there is no such string and such string is hard to search for and I can't send you the file in question because it is full of secrets.

**Comment by jidanni** [comment]
As a bonus also offer to give context AFTER the trouble spot too.
Or both:
```
Problem HERE:
22343,6546234,66562,35356 >>> ,, <<< 45234,5654654.56554.
```

**Comment by charsbar** [comment]
* JSON texts don't always have multiple lines so an option to show more lines is less useful.
* Showing more characters doesn't help because "invalid character" means ```/[\x00-\x1f\x22\x5c]/```, most of which are not printable.

I don't think there's a way to satisfy everyone about this. The error message may not be friendly, but it has enough information and the format is the same for both JSON::PP and JSON::XS (and other wrapper modules like JSON.pm). If you do need something more friendly, I'd recommend you to catch the error message and get the offset from it and show what you think is necessary with the help of ```substr()``` etc.

**Comment by charsbar** [comment]
Setting a flag to a specific context and reading the number in a different context is a user's issue we can't help. Showing more characters may help sometimes, but may not if the same sequence of characters occur in the JSON text again and again.

**Comment by jidanni** [comment]
"substr operates on 1-byte characters unless the string has the UTF-8 flag on."
It seems that also reporting a byte count would guarantee the user could finally pin down what spot the error message is talking about. Then he could use dd(1), head(1), etc. which is probably what he tries anyway.

**Comment by charsbar** [comment]
Again, it's user's responsibility to apply the same context for the number reported. JSON::PP only knows at what offset under the current context it is now.

**Comment by jidanni** [comment]
Fine, but many will first think "he must have meant bytes, not characters. No wonder I can't find it." OK, never mind.
